### ISSUE TITLE
[BUG]: Shortcuts does not work

### ISSUE THREAD

**Issue by distrair** [LGUG2Z/whkd#17]
**Describe the bug**
For some reason, shortcuts does not work. When I do some of the shortcuts, the console shows this error: `An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full. (os error 10055)`

**To Reproduce**
1. Put whkdrc in the .config folder
2. Launch whkd

**Expected behavior**
Shortcuts does work

**Screenshots and Videos**
![image](https://github.com/LGUG2Z/whkd/assets/78724291/e3d72677-83c2-4a6d-8212-9bd4aed6b0ac)

**Operating System**
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22621 N/A Build 22621

**Additional context**

In particular, if you have any other AHK scripts or software running that handle any aspect of window management, manipulation or hotkey binding

**Comment by LGUG2Z** [comment]
https://github.com/LGUG2Z/komorebi/issues/401 this issue is being tracked here
