### ISSUE TITLE
[BUG]: Terminate active window with hotkey

### ISSUE THREAD

**Issue by HasanAbbadi** [LGUG2Z/whkd#21]
**Describe the bug**
I can't seem to figure out a way to kill currently active and selected process with a hotkey in the whkdrc.
I'm not sure if this is my lack of powershell knowledge or a Windows limitation

**Expected behavior**
To close the currently active window.

**Operating System**
```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19045 N/A Build 19045
```

**Comment by LGUG2Z** [comment]
If you're using `komorebi` you could use the `komorebic close` command for this. I'm not sure exactly how this would be done with pure PowerShell...

**Comment by winstxnhdw** [comment]
This isn't working :/

```
alt + shift + q		: komorebic close
```

**Comment by winstxnhdw** [comment]
Looks like your <kbd>alt</kbd> + <kbd>o</kbd> binding is wrong.

You set it to

```ps1
taskkill /f /im whkd.exe && Start-Process whkd -WindowStyle hidden
```

When it is supposed to be

```ps1
taskkill /f /im whkd.exe; Start-Process whkd -WindowStyle hidden
```

PowerShell doesn't support `&&`.

**Comment by LGUG2Z** [comment]
Pipeline and chain operators have been available in PowerShell since 2019: https://github.com/PowerShell/PowerShell/pull/9849

It may be a case of having an older version of PowerShell installed. Nevertheless I think it's a good idea to support the oldest feasible version where possible; I'll make this change on the sample file.

**Comment by winstxnhdw** [comment]
Ah, you're right. It seems machine with PowerShell 5.1.1 won't just upgrade to 7 or later on Windows updates. Yikes.
