### ISSUE TITLE
WHKD cannot bind keys

### ISSUE THREAD

**Issue by chris-dem** [LGUG2Z/whkd#33]
I installed yasb and when I tried to conenct it with komorebi, my keybindings stopped working. When I run whkd I am getting this
![image](https://github.com/LGUG2Z/whkd/assets/26067498/8ddb5212-28e4-426f-b27f-a9d3518cbfaa)
Any ideas on how to solve this issue?

**Comment by LGUG2Z** [comment]
You most likely have multiple instances running. Kill all instances with `Stop-Process -Name:whkd` multiple times until you get a process not found error, and then try starting komorebi again with the `--whkd` flag.

**Comment by chris-dem** [comment]
If you try again on powershell it works fine. If you use `Terminal` it doesn't seem to work right
