### ISSUE TITLE
[BUG]: whkd unable to bind

### ISSUE THREAD

**Issue by WTanardi** [LGUG2Z/whkd#39]
**Describe the bug**
whkd cannot bind the hotkeys

**To Reproduce**
1. install komorebic normally via scoop on pwsh7
2. follow the tutorial
3. run komorebic quickstart
4. run komorebic start --whkd
5. komorebic starts but hotkeys don't work

**Expected behavior**
The hotkeys should work

**Screenshots and Videos**
![image](https://github.com/LGUG2Z/komorebi/assets/90451337/94c99aa6-4f43-4fd5-b16a-a5b023821767)

**Operating System**
Provide the output of `systeminfo | grep "^OS Name\|^OS Version"`

```
OS Name:                   Microsoft Windows 11 Home
OS Version:                10.0.22631 N/A Build 22631
```

**`komorebic check` Output**
Provide the output of `komorebic check`

```
No KOMOREBI_CONFIG_HOME detected, defaulting to C:\Users\willi

Looking for configuration files in C:\Users\willi

Found komorebi.json; this file can be passed to the start command with the --config flag

Found C:\Users\willi\.config\whkdrc; key bindings will be loaded from here when whkd is started, and you can start it automatically using the --whkd flag
```

**Additional context**
I have touchcursor on, I'm using an alternative layout (Halmak), I have powertoys on, I've done some configurations via sharpkeys

**Comment by LGUG2Z** [comment]
This is an error typical of trying to run more than once instance at a time. Make sure all processes of `whkd` are stopped by running `Stop-Process -name:whkd` until the command errors out, then run `whkd` itself in the foreground. If there are any errors or unsupported bindings, they will be reporting in the stdout.

**Comment by WTanardi** [comment]
upon running just whkd, this happens

![image](https://github.com/LGUG2Z/whkd/assets/90451337/6d0bbea5-7081-4358-a99b-bce78588b0d1)

**Comment by LGUG2Z** [comment]
This behaviour is sporadic and not really reproducible because people's OS settings are so different. I believe it you accept this once you shouldn't need to accept it again

**Comment by WTanardi** [comment]
the thing is I can't press anything into the console 😭, I'll try to find a fix to the PSReadline issue first, then I'll get back here if the problem persists

**Comment by chhoumann** [comment]
Encountered the exact same issues. Running `komorebic start --whkd --bar` in Command Prompt works for me.

**Comment by tylertylerday** [comment]
Same for me @chhoumann @WTanardi
