### ISSUE TITLE
[BUG] WHKD doesn't start

### ISSUE THREAD

**Issue by mmaldacker** [LGUG2Z/whkd#4]
**Describe the bug**
WHKD stops with an error during startup

```
Error:
   0: program not found

Location:
   src\main.rs:97
```

The code on line 97 seems to start a powershell but I don't see why that wouldn't work.

**Comment by LGUG2Z** [comment]
Can you share your config? Some systems have `powershell` but not `pwsh`; you can see whichever is on your path and set it accordingly at the top of the config file. You can also try setting `cmd` which will definitely be on your system.

**Comment by mmaldacker** [comment]
Yes, indeed I don't have `pwsh` and setting the config file to use `powershell` works thanks!

**Comment by tgienger** [comment]
Should show how to set it to run powershell or cmd
