### ISSUE TITLE
[BUG]: Inconsistent Window Activation

### ISSUE THREAD

**Issue by vec715** [LGUG2Z/whkd#40]
**Describe the bug**
Sometimes, a window could not be opened using a hotkey. For example, using the hotkey alt + b to open Google Chrome sometimes works fine, but other times the Chrome window flashes on the taskbar but does not become active

**To Reproduce**
1. Set up a hotkey to open Google Chrome using the following script:
```
alt + b                 : if ($wshell.AppActivate('Chrome') -eq $False) { start chrome }
```
2. Press alt + b to open Chrome.
3. Observe the behavior:
- Sometimes, Chrome opens and becomes the active window.
- Sometimes, the Chrome icon flashes on the taskbar, but the window does not become active.

**Expected behavior**
Pressing the hotkey alt + b should consistently open Google Chrome and make it the active window without just flashing on the taskbar.

**Operating System**
```
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22635 N/A Build 22635
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              LENOVO N3AET81W (1.46 ), 4/24/2024
```

**Additional context**
I am also using [ExplorerPatcher](https://github.com/valinet/ExplorerPatcher) to customize the Windows 11 taskbar and other elements. I am not sure if this might be causing the issue, but it could be related.

**Comment by LGUG2Z** [comment]
This isn't really a whkd issue but a PowerShell issue; I suggest raising it on the PowerShell tracker as this specifically concerns the behaviour of the `start` command and not `whkd`.
