### ISSUE TITLE
[BUG]: WHKD_CONFIG_HOME - custom config dir not being respected?

### ISSUE THREAD

**Issue by IAmIlliest** [LGUG2Z/whkd#41]
**Describe the bug**
Appears to be ignoring or unable to interpret a path, when `$Env:WHKD_CONFIG_HOME` is set.

**To Reproduce**
A clean install of komorebi and whkd, which is being scripted as below in pwsh:
```
# Install
#########

# install setup:
$config_dir_komo = "${Env:XDG_CONFIG_HOME}\komorebi"
$config_dir_whkd = "${config_dir_komo}\whkd"
$add_to_profile = @"

###################
# Komorebi Config #
###################
`$Env:KOMOREBI_CONFIG_HOME = '${config_dir_komo}'
`$Env:WHKD_CONFIG_HOME = '${config_dir_whkd}'
"@ -split '\n'

# apply setup:
mkdir -p $config_dir_komo
mkdir -p $config_dir_whkd
Add-Content -Path $PROFILE $add_to_profile
. $PROFILE

# install komorebi:
winget install LGUG2Z.komorebi LGUG2Z.whkd
```
That script bolts the following to the end of $PROFILE and then dot sources $PROFILE before installing via winget:
```

###################
# Komorebi Config #
###################
$Env:KOMOREBI_CONFIG_HOME = 'D:\XDG\config\komorebi'
$Env:WHKD_CONFIG_HOME = 'D:\XDG\config\komorebi\whkd'
```
So all the paths are being interpreted correctly, and sourced into the shell correctly prior to the winget install commands. Output from querying those env vars in the shell prior to running winget:
```
(base) PS C:\Users\kiham> $Env:WHKD_CONFIG_HOME
D:\XDG\config\komorebi\whkd
(base) PS C:\Users\kiham> $Env:KOMOREBI_CONFIG_HOME
D:\XDG\config\komorebi
```

**Expected behavior**
At the end of that script, I expected to see whkdrc land in `D:\XDG\config\komorebi\whkd` (or at least: `~/.config/whkdrc`).
It actually doesn't seem to be turning up anywhere at all?

**Operating System**
```
OS Name:                   Microsoft Windows 10
```

**Comment by LGUG2Z** [comment]
I may be missing something reading this on mobile, but I don't see any command in your script that would generate a whkdrc file?

whkd itself doesn't ship with a configuration file, and I don't see the "komorebic quickstart" command here which would generate a whkdrc file being called here

**Comment by IAmIlliest** [comment]
Ah sorry, that was me missing those commands when I copied it:
```
# Quickstart
############
komorebic quickstart
komorebic start --config $Env:KOMOREBI_CONFIG_HOME\komorebi.json --whkd
```
I've now nuked the folders/files a couple of times and `komorebi quickstart` is putting whkdrc in the default path, even if $Env:WHKD_CONFIG_HOME is set. You can see `(base) PS C:\Users\kiham> dir $Env:WHKD_CONFIG_HOME` returning nothing below, and the file popping up in the default path:

```
(base) PS C:\Users\kiham> Write-Host "$Env:KOMOREBI_CONFIG_HOME`n$Env:WHKD_CONFIG_HOME"
D:\XDG\config\komorebi
D:\XDG\config\komorebi\whkd
(base) PS C:\Users\kiham> dir $Env:KOMOREBI_CONFIG_HOME

    Directory: D:\XDG\config\komorebi

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           2/06/2024    15:05                whkd

(base) PS C:\Users\kiham> dir $Env:WHKD_CONFIG_HOME
(base) PS C:\Users\kiham> komorebic quickstart
Example ~/komorebi.json, ~/.config/whkdrc and latest ~/applications.yaml files downloaded
You can now run komorebic start --whkd
(base) PS C:\Users\kiham> dir $Env:KOMOREBI_CONFIG_HOME

    Directory: D:\XDG\config\komorebi

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           2/06/2024    15:05                whkd
-a---           3/06/2024    15:10          29380 applications.yaml
-a---           3/06/2024    15:10           1389 komorebi.json

(base) PS C:\Users\kiham> dir $Env:WHKD_CONFIG_HOME
(base) PS C:\Users\kiham> dir "$Env:USERPROFILE/.config"

    Directory: C:\Users\kiham\.config

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          18/05/2024    15:20                Lumina
d----           1/10/2021    17:18                scoop
-a---           3/06/2024    15:10           3339 whkdrc
```

Sorry, I did start trying to debug the path handling of the main.rs for whkd in VSCode, but after an hour or so of failing had to admit to myself that I had no idea what I was doing....

**Comment by IAmIlliest** [comment]
Thanks for the great application by the way, appreciate all the effort you put into both komorebi and whkd. Your timing on the nixOs WSL is fortuitous too, had been looking into excatly that myself yesterday, as an alternative to building a dev environment directly in a container...Since I can't post links in YT:
https://github.com/nix-community/NixOS-WSL
https://yashgarg.dev/blog/nix-devenv

**Comment by LGUG2Z** [comment]
With the latest version of `komorebic` on `master` this should now be fixed with `whkdrc` getting created in the folder specified by `WHKD_CONFIG_HOME` 🎉  https://github.com/LGUG2Z/komorebi/issues/861#issuecomment-2143912472
