### ISSUE TITLE
[BUG]: whkd error

### ISSUE THREAD

**Issue by Nyxendoescode** [LGUG2Z/whkd#44]
**Describe the bug**
when starting komorebi this happens
![Screenshot 2024-08-16 193601](https://github.com/user-attachments/assets/310fe7ad-bc65-40d3-9715-5e76807ddc48)
![Screenshot 2024-08-16 193700](https://github.com/user-attachments/assets/ce0b8047-0283-4b7b-85aa-2b3427a5f746)

**To Reproduce**
1. used the command "komorebic start --whkd"

**Expected behavior**
start normally with no errors

**Operating System**

```
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22631 N/A Build 22631
```

**Comment by dinesh-58** [comment]
This is because there is already a whkd process running. You can check this with `Get-Process whkd`. This issue can be closed
