### ISSUE TITLE
[BUG]: Possible deadlock

### ISSUE THREAD

**Issue by azais-corentin** [LGUG2Z/whkd#48]
**Describe the bug**
Hello,
I'm using whkd with komorebi and sometimes whkd seem to get stuck.
Hotkeys stop working entirely.

I am also using PowerToys and AltSnap at the same time.
The configuration is very similar to the default. I'm using powershell (7.4.5).

Stopping whkd using the command `komorebic stop --whkd` does not work.
Killing the task using task manager works.

It doesn't happen too often but more than once a day so far. 
I will update this post whenever I can reproduce the bug.

Is there anything similar to the `deadlock_detection` feature in komorebi?

**To Reproduce**
Unknown yet. I will update when I have more information.

**Expected behavior**
No deadlock.

**Operating System**

```
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22621 N/A Build 22621
```

**Comment by Haider-Mirza** [comment]
On my system, I can reliably get whkd to stop registering inputs if I just spam keys (like the ones set for switching workspaces). You could check if this can cause the issue.

**Comment by LGUG2Z** [comment]
The issue has been verified to be in komorebi. Closing this issue as there is nothing to be done here.
