### ISSUE TITLE
[BUG]: whkd cannot re-start

### ISSUE THREAD

**Issue by gonglei** [LGUG2Z/whkd#5]
I tried to change config file ~/.config/whkdrc, but cannot re-start it any more after it is killed. I followed this command:

taskkill /f /im whkd.exe && Start-Process whkd -WindowStyle hidden

While I cannot see this process any more when I try to find it: tasklist | findstr whkd

**To Reproduce**
1. taskkill /f /im whkd.exe && Start-Process whkd -WindowStyle hidden
2. tasklist | findstr whkd
3. wkhd is not in tasklist, no hotkey works

**Expected behavior**
The whkd process should be started and hotkeys work

**Screenshots and Videos**
Add screenshots and videos to help explain your problem.

**Operating System**
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22000 N/A Build 22000

**Additional context**

In particular, if you have any other AHK scripts or software running that handle any aspect of window management, manipulation or hotkey binding

**Comment by LGUG2Z** [comment]
```
~
❯ whkd
# pressed alt + o here to trigger the line below
taskkill /f /im whkd.exe && Start-Process whkd -WindowStyle hidden
SUCCESS: The process "whkd.exe" with PID 2620 has been terminated.

~ took 2s
❯ tasklist | findstr whkd
whkd.exe                     10504 Console                    1      7,748 K
```

Unfortunately I am unable to reproduce this. Could you share your configuration file so that I can try again to reproduce it with your settings?

**Comment by gonglei** [comment]
It could be caused by an error in whkdrc. I tried to change alt to win in it but not successful, I guess that was an error and whkd not started. I restored it back and it can be started again. thanks.

**Comment by LGUG2Z** [comment]
I think this is the case; if something in the configuration triggers an error, the process will not be successfully restarted.
